### ISSUE TITLE
Email: Invalid Redirect Info

### ISSUE THREAD

**Issue by AOD-Tracker** [flashadvocate/Division-Tracker#103]
When sending emails to squad members through the tracker, after filling out the subject and the contents of the email, the AOD site gives an error message, invalid redirect info.<hr /><strong>Page reported</strong>: http://www.clanaod.net/forums/sendmessage.php?do=mailmember&u=37319 or any email sent to any user.<br /><strong>Reported by</strong>: DaerthanWarp

**Comment by flashadvocate** [comment]
This is caused by the tracker linking directly to the email form, and so the forum doesn't like redirecting to a different domain.
