### ISSUE TITLE
Blank recruit under FirePhoenix

### ISSUE THREAD

**Issue by AOD-Tracker** [flashadvocate/Division-Tracker#109]
https://gyazo.com/726107b2b3f11897e33aebc9b06c8451

4th from the bottom of Fire's squad there is a blank recruit, that provides an 500 Internal Server Error if clicked on.<hr /><strong>Page reported</strong>: http://aodwebhost.site.nfoservers.com/tracker/divisions/bf/platoon/6<br /><strong>Reported by</strong>: tboose7

**Comment by flashadvocate** [comment]
This has been fixed
