### ISSUE TITLE
Removing Group/Platoon Squads

### ISSUE THREAD

**Issue by AOD-Tracker** [flashadvocate/Division-Tracker#169]
I have a button to create NEW squads, but not to REMOVE squads if they are empty and/or have no Squad Lead.

I'd like to get rid of my 3 TBA in the SPEC platoon/group<strong>Reported by</strong>: Kestah

**Comment by flashadvocate** [comment]
Fixed in https://github.com/flashadvocate/Division-Tracker/commit/76b8365b13857d27b8bf506c10f74e43e2e4d251
