### ISSUE TITLE
`games` -> `divisions`, add games table

### ISSUE THREAD

**Issue by gofishAOD** [flashadvocate/Division-Tracker#34]
to support sub-games in BF4. This could also be done probably as a function, since we're the only division that will be set up to umbrella multiple games. 

* needs to use the public/images/game_icons that are provided, or add them if they don't already exist
* needs to have a games column, where a user can have multiple games, or just one game.
* need a way to modify the games a user has, and this needs to be something users can do to themselves.

**Comment by flashadvocate** [comment]
This is done
